services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    command: npm run dev -- --host
  api:
      build: ./api
      environment:
        - TZ=America/Sao_Paulo  
      volumes:
        - ./api:/api
      ports:
        - "5174:5174"
